ci:
  collect:
    autodiscover-url-blocklist: /privacy-policy.html
  upload:
    target: "temporary-public-storage"
  assert:
    assertions:
      categories:performance: error
      categories:accessibility: error
      categories:best-practices: error
      categories:seo: error
