ci:
  collect:
    autodiscover-url-blocklist: /privacy-policy.html
  upload:
    target: "temporary-public-storage"
  assert:
    preset: "lighthouse:no-pwa"
    assertions:
      csp-xss: "off"
      bf-cache: "warn"
      is-crawlable: "off"
      robots-txt: "off"
      meta-description: "off"
      total-byte-weight: ["error", { "maxNumericValue": 1677721600 }] # TODO: remove this when this bug is fixed: https://github.com/GoogleChrome/lighthouse-ci/issues/994
